### ISSUE TITLE
INDI Web

### ISSUE THREAD

**Issue by rankinstudio** [sebo-b/TicFocuser-ng#3]
Is there a way to add Tic Focuser NG to the INDI Web manager?

Thanks

**Comment by sebo-b** [comment]
Hi,

I don't have the setup right now in front of me, but I was using it via INDI Web Manager without any issues - it should just appear there.

Regards.

**Comment by rankinstudio** [comment]
My setup is Astroberry (PI4) => Windows 10 Laptop. It didn't seem to show up in the INDI Web manager on astroberry. I had to manually add it to the Ekos devices list on my Windows machine and it boots up fine now.

Also, thank you. This project is awesome and saved me a lot of $. 

Cheers
