### ISSUE TITLE
Starting at 0

### ISSUE THREAD

**Issue by rankinstudio** [sebo-b/TicFocuser-ng#5]
Hey, wondering if there is a way to start it at like 2000 steps in INDI? It starts at 0 and I can't seem to get it to save differently. It won't let me focus in unless I manually re-sync it to like 2000 in the INDI panel. 

Cheers

**Comment by sebo-b** [comment]
The position in the driver is synchronized with the position in the Tic controller. You can check in ticgui if there is a possibility to set start position, but AFAIR there is not.

With this being said, you should start your setup with a focuser at its lowest position, so it is 0 and there is no issue of moving farther inward.
