### ISSUE TITLE
Backlash compensation

### ISSUE THREAD

**Issue by LionBit76** [sebo-b/TicFocuser-ng#7]
I've built a focuser [https://github.com/LionBit76/MagneTicFocuser](url) that has gearing to run it on as little as 1mA. Of course there is some play in the gearbox. What I'm missing now is the backlash compensation in the driver. Would it be possible to add this function to the driver?

Greetings
Luke

**Comment by sebo-b** [comment]
It looks really nice - congratulations!

Backlash compensation shouldn't be very hard to be implemented, and IIRC there is even support for that in the base class of indi focuser. With this being said, I was not working on this project for months, and currently, I don't have much time to look at it. If you are willing to contribute with your changes, I will be happy to review and accept the pull request.

**Comment by sebo-b** [comment]
Ahh... backlash compensation was added in this pull request: https://github.com/sebo-b/TicFocuser-ng/pull/4

However, I have never tested it. Feel free to reach out to [lbru](https://github.com/lbru) for more details.
