### ISSUE TITLE
tic focuser ng reinstall unpossible

### ISSUE THREAD

**Issue by Leforgeron-42** [sebo-b/TicFocuser-ng#8]
Hello
I'm not a computer person and I'm a bit messy. I had installed tic focuser ng on raspberry pi 64 with stellarmate.
I was very happy with how it worked. Then I had a power outage at night which forced me to reinstall everything on my pi 4. I can no longer reinstall tic Focuser-Ng because after having built the Build I have a message of error telling me that in line 7 of CMakeLists.txt no CXX compiler found.
Can you help me ?
Thanks . Sorry for my English.

**Comment by sebo-b** [comment]
seems that you don't have a c++ compiler installed, try to install build-essential
```
sudo apt-get install build-essential
```

**Comment by Leforgeron-42** [comment]
HiThanks a lot for your Help the focuser run and apear in EKOS but do not apear with de Zwo CCD ASI 533 for focusing.I'm able to st paramètres and position in the setting windows i can move the focuser vith the 3 positions setting.When i open the focusing window ther is no list of focuseur to choose. I look,more for that.Thanks for your help.envoyé : 23 novembre 2022 à 00:40de : sebo-b ***@***.***>à : sebo-b/TicFocuser-ng ***@***.***>cc : Leforgeron-42 ***@***.***>, Author ***@***.***>objet : Re: [sebo-b/TicFocuser-ng] tic focuser ng reinstall unpossible (Issue #8) seems that you don't have a c++ compiler installed, try to install build-essentialsudo apt-get install build-essential

**Comment by Leforgeron-42** [comment]
Oups i forgot to set the devices running with the ccd.Sorry.Thank a lot.envoyé : 23 novembre 2022 à 00:40de : sebo-b ***@***.***>à : sebo-b/TicFocuser-ng ***@***.***>cc : Leforgeron-42 ***@***.***>, Author ***@***.***>objet : Re: [sebo-b/TicFocuser-ng] tic focuser ng reinstall unpossible (Issue #8) seems that you don't have a c++ compiler installed, try to install build-essentialsudo apt-get install build-essential

**Comment by sebo-b** [comment]
ok - so I understand that it is fixed and the issue can be closed.

**Comment by Leforgeron-42** [comment]
Hi sebo-b
Yes thanks it run well.
Clear Sky.
Régis.
 
Envoyé depuis l'application Mail Orange
----------------De : sebo-b ***@***.***>Envoyé : mercredi 23 novembre 2022 21:29À : sebo-b/TicFocuser-ng ***@***.***>Cc : Leforgeron-42 ***@***.***>; Author ***@***.***>Objet : Re: [sebo-b/TicFocuser-ng] tic focuser ng reinstall unpossible (Issue #8)
ok - so I understand that it is fixed and the issue can be closed.
